### ISSUE TITLE
Mouse reference genome on Hiplot

### ISSUE THREAD

**Issue by tecnicalferre13** [ShixiangWang/install_GISTIC#11]
Dear Shixiang, is it possible to add a mouse reference genome (GRCm38, by Lange et. al., https://github.com/roland-rad-lab/MoCaSeq/blob/master/data/GRCm38.Gistic_reference.mat) to the other ref genomes on Hiplot?

Cheers, 
SBurger

**Comment by ShixiangWang** [comment]
Hi @tecnicalferre13 

Based on the setting in https://github.com/ShixiangWang/install_GISTIC/blob/master/run_docker.sh, we could not put reference file outside docker. So you install install it locally and switch the reference file by your own.
