### ISSUE TITLE
安装MATLAB环境的报错

### ISSUE THREAD

**Issue by lizhan96** [ShixiangWang/install_GISTIC#12]
我通过`wget -c ftp://ftp.broadinstitute.org/pub/GISTIC2.0/GISTIC_2_0_23.tar.gz`下载和解压之后进行MCR的安装，出现了以下的报错。

> java.lang.UnsatisfiedLinkError: /tmp/mathworks_29386/sys/java/jre/glnxa64/jre/lib/amd64/xawt/libmawt.so: libXi.so.6: cannot open shared object file: No such file or directory

**Comment by ShixiangWang** [comment]
这跟这个仓库有什么关系呢？

如果你想本地安装gistic2，请按照https://github.com/ShixiangWang/install_GISTIC的说明进行。

**Comment by lizhan96** [comment]
但安装gistic2之前不是要先配置MATLAB环境吗？

**Comment by ShixiangWang** [comment]
不需要。你按照操作说明操作看看。（仅限Linux）

**Comment by lizhan96** [comment]
您好，我运行$git clone https://github.com/ShixiangWang/install_GISTIC之后还是无法成功安装，报错信息如下。

Cloning into 'install_GISTIC'...
/usr/lib/git-core/git-remote-https: /data_6t/lizhan/02.software/MCR/v912/bin/glnxa64/libldap_r-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
/usr/lib/git-core/git-remote-https: /data_6t/lizhan/02.software/MCR/v912/bin/glnxa64/liblber-2.4.so.2: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4)
fatal: unable to access 'https://github.com/ShixiangWang/install_GISTIC/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

希望能得到您的帮助。

**Comment by lizhan96** [comment]
删掉我自己安装的MATLAB环境后就成功运行了。谢谢。
