### ISSUE TITLE
Instrall GISTIC2 errors.

### ISSUE THREAD

**Issue by tanbiswas** [ShixiangWang/install_GISTIC#15]
Hello,
While installing GISTIC 2 I gor this erroe and can not install GISTIC. Please let me know how to solve this and install GISTIC2. Below is the full command and errors.

```
[](lab4@lab4-Vostro-3800:~/install_GISTIC$ ./install_GISTIC2.sh /home/lab4/gistic2-2.0.23.tar.gz /home/lab4/GISTIC2/
=================
  Preparing...  
=================
Directory created.
=================
  Unzipping...  
=================
gistic2-2.0.23/
gistic2-2.0.23/.gitignore
gistic2-2.0.23/LICENSE
gistic2-2.0.23/README.md
gistic2-2.0.23/source/
gistic2-2.0.23/source/@SegArray/
gistic2-2.0.23/source/@SegArray/SegArray.m
gistic2-2.0.23/source/@SegArray/abs.m
gistic2-2.0.23/source/@SegArray/addSegments.m
gistic2-2.0.23/source/@SegArray/all.m
.
.
.
.
gistic2-2.0.23/support/gp_gistic2_from_seg
gistic2-2.0.23/support/refgenefiles/
gistic2-2.0.23/support/refgenefiles/hg16.mat
gistic2-2.0.23/support/refgenefiles/hg17.mat
gistic2-2.0.23/support/refgenefiles/hg18.mat
gistic2-2.0.23/support/refgenefiles/hg19.UCSC.add_miR.140312.refgene.mat
gistic2-2.0.23/support/refgenefiles/hg19.mat
gistic2-2.0.23/support/refgenefiles/hg38.UCSC.add_miR.160920.refgene.mat
gistic2-2.0.23/support/release_gistic_source.sh
gistic2-2.0.23/support/run_gistic_example
./install_GISTIC2.sh: line 54: cd: MCR_Installer/: No such file or directory
unzip:  cannot find or open MCRInstaller.zip, MCRInstaller.zip.zip or MCRInstaller.zip.ZIP.
=================
  Installing...  
=================
./install_GISTIC2.sh: line 62: ./install: No such file or directory
==================================
Seting environmanet variables..
==================================
==================
    Testing...  
Please be patient
==================
./install_GISTIC2.sh: line 78: ./run_gistic_example: No such file or directory
Test failed, please check the errors above.
Typically, the errors are due to lack of some system dependencies.
    Please search the QA on internet or file to https://github.com/ShixiangWang/install_GISTIC/issues
lab4@lab4-Vostro-3800:~/install_GISTIC$)
```

Please let me know how to solve this.
Thank you.

**Comment by ShixiangWang** [comment]
What's your operating system? The script has not been updated for a long time as it is well-tested. So I guess you are working on a machine that may not suit it well.

May you try https://hiplot.cn/advance/gistic2 on hiplot or just use the docker image https://hub.docker.com/r/shixiangwang/gistic/tags?

**Comment by tanbiswas** [comment]
Hi Wang,

I'm using Ubuntu 22.04 LTS. I put GISTIC2 run on hiplot but it is showing run finished but it has nor generated the outputs. I also tried to use docker image which is also not working and below is the command:

iit@iit:/Toolkit$ docker pull shixiangwang/gistic:latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=shixiangwang%2Fgistic&tag=latest": dial unix /var/run/docker.sock: connect: permission denied

Please let me know how to install it.
Thank you.

**Comment by ShixiangWang** [comment]
I just tested hiplot, it works well.

![image](https://user-images.githubusercontent.com/25057508/236380570-1d76db5f-7cf8-45fb-a139-34fc51217973.png)


For docker, you need to use `sudo docker pull shixiangwang/gistic:latest` when you have no permission.

**Comment by tanbiswas** [comment]
I'm getting like this in hiplot:
/home/lab4/Screenshots/Screenshot from 2023-05-05 10-55-58.png

**Comment by tanbiswas** [comment]
While using from docker it is now showing the below error:

(base) root@a69acdea8e3f:/opt/GISTIC# unset DISPLAY
(base) root@a69acdea8e3f:/opt/GISTIC# basedir= /media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/GISTIC2
bash: /media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/GISTIC2: No such file or directory
(base) root@a69acdea8e3f:/opt/GISTIC# basedir="/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/GISTIC2"
(base) root@a69acdea8e3f:/opt/GISTIC# segfile="/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/gistic2_input_32_samples.txt"
(base) root@a69acdea8e3f:/opt/GISTIC# refgenefile="/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/refgenefiles/hg38.UCSC.add_miR.160920.refgene.mat"
(base) root@a69acdea8e3f:/opt/GISTIC# ./gistic2 -b $basedir -seg $segfile -refgene $refgenefile -rx 0 -genegistic 1 -smallmem 1 -broad 1 -brlen 0.5 -twosize 1 -armpeel 1 -savegene 1 -maxseg 10000 -conf 0.99
Setting Matlab MCR root to /opt/GISTIC/MATLAB_Compiler_Runtime
 
GISTIC 2.0 input error:
Base directory '/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/GISTIC2' does not exist
 
Usage: gp_gistic2_from_seg -b base_dir -seg segmentation_file
-refgene ref_gene_file  [-mk markers_file] [-alf array_list_file(def:empty)]
[-cnv cnv_file] [-ta amplifications_threshold(def=.1)] [-td deletions_threshold(def=.1)]
[-js join_segment_size(def=8)] [-ext extension] [-qvt qv_thresh(def=0.25)]
[-rx remove_x(def=1)] [-v verbosity_level(def=0)] [-cap cap_val(def=1.5]]
[-broad run_broad_analysis(def=0)] [-brlen broad_length_cutoff(def=0.98)]
[-maxseg max_sample_segs(def=2500)] [-res res(def=0.05)] [-conf conf_level(def=0.75)]
[-genegistic do_gene_gistic(def=0)] [-smalldisk save_disk_space(def=0)]
[-smallmem use_segarray(def=1)] [-savegene write_gene_files(def=0)]
[-arb do_arbitration(def=1)] [-twosides use_two_sided(def=0)] [-peaktype peak_types(def=robust)]
[-saveseg save_seg_data(def=1)] [-savedata write_data_files(def=1)]
[-armpeel armpeel(def=1)] [-gcm gene_collapse_method(def=mean)]
[-scent sample_center(def=median)] [-maxspace max_marker_spacing]
[-logdat islog(def=auto-detect)]
(base) root@a69acdea8e3f:/opt/GISTIC# 

The directory exist. But still it is showing does not exist

**Comment by ShixiangWang** [comment]
What's the result of `sudo docker run -it --rm --entrypoint bash shixiangwang/gistic` outside from the docker image?

**Comment by tanbiswas** [comment]
iit@iit:/Toolkit$ sudo docker run -it --rm --entrypoint bash shixiangwang/gistic
[sudo] password for iit: 
(base) root@1b1b04bdea02:/opt/GISTIC#

**Comment by ShixiangWang** [comment]
Next, try running the example script outside the image. The script is available from https://github.com/ShixiangWang/install_GISTIC/blob/master/run_docker.sh

```
./run_docker.sh
```

**Comment by tanbiswas** [comment]
I checked the docker script. I have one query. Do I need to specify both of these in as an input file?

#segfile=/path/to/your/input.seg     ------This should be my input file
segfile=$GISTIC_LOC/examplefiles/segmentationfile.txt  -----should I need to mention this code as well?

Please let me know.

**Comment by ShixiangWang** [comment]
> Do I need to specify both of these as an input file? #segfile=/path/to/your/input.seg ------This should be my input file segfile=$GISTIC_LOC/examplefiles/segmentationfile.txt -----should I need to mention this code as well?

The script is self-contained and runs with the example data, i.e., `segfile=$GISTIC_LOC/examplefiles/segmentationfile.txt` here. If you use your own data, you should comment this, and uncomment and modify `#segfile=/path/to/your/input.seg`.

Has the example workflow been executed successfully?

**Comment by tanbiswas** [comment]
Yes. The example file ran successfully. But I am still figuring out how to use my file as an input as I've never used docker before.

I have used like this:

iit@iit:/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit$ #segfile=/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/gistic2_input_32_samples.txt 
segfile=$GISTIC_LOC/examplefiles/segmentationfile.txt

Is it correct?

**Comment by ShixiangWang** [comment]
Go outside the image.

```
mkdir test_results
cp /media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/gistic2_input_32_samples.txt test_results
```

Then modify `segfile=$GISTIC_LOC/examplefiles/segmentationfile.txt` to `segfile=$OUTDIR/gistic2_input_32_samples.txt` in the `run_docker.sh`.

Then run with `bash run_docker.sh`.

**Comment by tanbiswas** [comment]
It is showing up  the following error. I think somehow it is not able to access the file location.
Her's the error:

iit@iit:/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit$ 
sudo docker run --rm -v $basedir:$DOCKER_OUTDIR \
  shixiangwang/gistic -b $DOCKER_OUTDIR -seg $segfile -refgene $refgenefile \
  -rx 0 -genegistic 1 -smallmem 1 -broad 1 -brlen 0.5 -twosize 1 \
  -armpeel 1 -savegene 1 -maxseg 10000 -conf 0.99
Going to /opt/GISTIC
Setting Matlab MCR root to /opt/GISTIC/MATLAB_Compiler_Runtime
 
GISTIC 2.0 input error:
Segmentation file '/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit/test_results/gistic2_input_32_samples.txt' does not exist
 
Usage: gp_gistic2_from_seg -b base_dir -seg segmentation_file
-refgene ref_gene_file  [-mk markers_file] [-alf array_list_file(def:empty)]
[-cnv cnv_file] [-ta amplifications_threshold(def=.1)] [-td deletions_threshold(def=.1)]
[-js join_segment_size(def=8)] [-ext extension] [-qvt qv_thresh(def=0.25)]
[-rx remove_x(def=1)] [-v verbosity_level(def=0)] [-cap cap_val(def=1.5]]
[-broad run_broad_analysis(def=0)] [-brlen broad_length_cutoff(def=0.98)]
[-maxseg max_sample_segs(def=2500)] [-res res(def=0.05)] [-conf conf_level(def=0.75)]
[-genegistic do_gene_gistic(def=0)] [-smalldisk save_disk_space(def=0)]
[-smallmem use_segarray(def=1)] [-savegene write_gene_files(def=0)]
[-arb do_arbitration(def=1)] [-twosides use_two_sided(def=0)] [-peaktype peak_types(def=robust)]
[-saveseg save_seg_data(def=1)] [-savedata write_data_files(def=1)]
[-armpeel armpeel(def=1)] [-gcm gene_collapse_method(def=mean)]
[-scent sample_center(def=median)] [-maxspace max_marker_spacing]
[-logdat islog(def=auto-detect)]
iit@iit:/media/iit/f2bf4ae5-e0cd-4f34-9453-b6a8e1a665e21/Toolkit$

**Comment by ShixiangWang** [comment]
Please follow the instructions above. As your path outside the docker not be mounted to the docker image, it will not be able to access the file.

**Comment by tanbiswas** [comment]
It ran successfully on hiplot platform. How ever the results were much questionable. I'm posting a separate issue for that.
Thanks.
