### ISSUE TITLE
unable to start from docker desktop

### ISSUE THREAD

**Issue by pacificma** [ShixiangWang/install_GISTIC#17]
Hi @ShixiangWang ,
I am trying to pull your docker image and run analysis from a win10 PC. When I am trying to start the image from docker desktop, it returns me some error msg: 

2023-05-19 17:27:57 GISTIC 2.0 input error:
2023-05-19 17:27:57 Must supply a base directory.

Also I followed the steps in bash command line, it was not working either, with error: docker: command not found or singularity: command not found

Do you have any idea how to fix it?

Thank you!

**Comment by ShixiangWang** [comment]
Dear @pacificma, the tool cannot work on Windows. You can use hiplot org platform https://hiplot.cn/advance/gistic2

**Comment by pacificma** [comment]
Thank you for the notice, I have already tried on hiplot.
