### ISSUE TITLE
GISTIC 2.0 input error detected: All input data were removed after NaN processing.

### ISSUE THREAD

**Issue by zzmaoyuqing** [ShixiangWang/install_GISTIC#18]
Hello,thanks for your 'preprocess.R' script to solve the problem of 'segment overlaps'. But after run the R script, there has a new problem which is "GISTIC 2.0 input error detected: All input data were removed after NaN processing." I have no idea how to solve the problem. If possible, I would appreciate your reply.
![屏幕截图 2024-06-16 195733](https://github.com/ShixiangWang/install_GISTIC/assets/41933213/a86f42eb-ce62-438e-a7e1-be2769783406)

**Comment by ShixiangWang** [comment]
Hi, please check the code with your data <https://github.com/ShixiangWang/install_GISTIC/blob/master/preprocess.R>. Based on info above, I cannot figure out where the issue came from, may be input data issue or software environment problem

**Comment by zzmaoyuqing** [comment]
谢谢王老师的回复，的确是我seg文件的问题，已解决。感谢！

**Comment by ShixiangWang** [comment]
Got it

**Comment by lucky999999999999999** [comment]
> 谢谢王老师的回复，的确是我seg文件的问题，已解决。感谢！
您好，我遇到了同样的问题，请问您是怎么解决的，谢谢
