### ISSUE TITLE
./gp_gistic2_from_seg: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory”

### ISSUE THREAD

**Issue by ShixiangWang** [ShixiangWang/install_GISTIC#2]

**Comment by ShixiangWang** [comment]
这个是系统缺乏共享库导致的，安装之后应该就能解决。

你能否尝试下 https://blog.51cto.com/lidaxia/1920745 提到的解决办法。

另外你能否提供一下你使用的是什么操作系统和运行安装时全部的输出信息？

**Comment by zhongjiehui** [comment]
您好！以下为我在Windows10子系统kali linux安装GISTIC2.0过程中出现的error:

On the target computer, append the following to your LD_LIBRARY_PATH environment variable:

/home/kali/install_GISTIC/GISTIC2/MATLAB_Compiler_Runtime/v83/runtime/glnxa64:/home/kali/install_GISTIC/GISTIC2/MATLAB_Compiler_Runtime/v83/bin/glnxa64:/home/kali/install_GISTIC/GISTIC2/MATLAB_Compiler_Runtime/v83/sys/os/glnxa64:



Next, set the XAPPLRESDIR environment variable to the following value:

/home/kali/install_GISTIC/GISTIC2/MATLAB_Compiler_Runtime/v83/X11/app-defaults


(Feb 21, 2020 23:10:32) Exiting with status 0
(Feb 21, 2020 23:10:32) End - Successful.
Finished
==================================
Seting environmanet variables..
==================================
==================
    Testing...
Please be patient
==================
--- creating output directory ---
--- running GISTIC ---
Setting Matlab MCR root to /home/kali/install_GISTIC/GISTIC2/MATLAB_Compiler_Runtime
./gp_gistic2_from_seg: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
Install finished, have fun!
-- Shixiang

**Comment by ShixiangWang** [comment]
你用的系统是Debian系列的，你可以搜一下Ubuntu怎么解决这个问题，一般是安装相应的库文件

**Comment by ShixiangWang** [comment]
@zhongjiehui 现在加入了 docker文件，你可以使用 docker 解决安装问题。

**Comment by Tianqi-Ma** [comment]
For those cannot access the blog mentioned above, [this link](https://stackoverflow.com/questions/17005654/error-while-loading-shared-libraries-libncurses-so-5) may be helpful.

**Comment by ShixiangWang** [comment]
> For those cannot access the blog mentioned above, [this link](https://stackoverflow.com/questions/17005654/error-while-loading-shared-libraries-libncurses-so-5) may be helpful.

great
