### ISSUE TITLE
"Install directory exists" error

### ISSUE THREAD

**Issue by abkhan90** [ShixiangWang/install_GISTIC#6]
Hello! I am getting some error when using this. Any help is appreciated. 

Following the command line prompts:
```

(base) abkhan@Abduls-MacBook-Pro GISTIC % git clone https://github.com/ShixiangWang/install_GISTIC

Cloning into 'install_GISTIC'...
remote: Enumerating objects: 119, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 119 (delta 63), reused 56 (delta 23), pack-reused 0
Receiving objects: 100% (119/119), 22.24 KiB | 5.56 MiB/s, done.
Resolving deltas: 100% (63/63), done.
(base) abkhan@Abduls-MacBook-Pro GISTIC % cd install_GISTIC
(base) abkhan@Abduls-MacBook-Pro install_GISTIC % chmod u+x install_GISTIC2.sh
```

These work successfully. But the next steps do not.

```
(base) abkhan@Abduls-MacBook-Pro install_GISTIC % ./install_GISTIC2.sh /Applications/GISTIC/GISTIC_2_0_23.tar.gz /Users/abkhan/Desktop
MacOS is detected, the GISTIC2 is for Linux at default, just take a try...
=================
  Preparing...  
=================
The install directory exists, exiting...
```

I did download the the gistic file and it appears in the directory using ls command:

```
(base) abkhan@Abduls-MacBook-Pro GISTIC % ls
GISTIC_2_0_23.tar   install_GISTIC
```
Any thoughts?

**Comment by ShixiangWang** [comment]
The tool may not work in MacOS, please use the docker image. You can also try free service at <https://hiplot.com.cn/advance/gistic2>

**Comment by abkhan90** [comment]
Thank you for your generous help!

Please excuse the novice questions, but I am trying to generate a .gistic output file for use in MAFtools for integrated WES analysis. Can I get this file from hiplot?

Additionally, how do I set the file path in the docker container for my seg file when it is located on my computer?

Again thanks!

**Comment by ShixiangWang** [comment]
Yeah, all output from GISTIC will be outputed from hiplot. You can try the example.

If you want to run docker by your own,  see https://github.com/ShixiangWang/install_GISTIC/blob/master/run_docker.sh
