### ISSUE TITLE
error in preparing 

### ISSUE THREAD

**Issue by ayue2019** [ShixiangWang/install_GISTIC#7]
`./install_GISTIC2.sh /home/data/vip25/software/GISTIC_2_0_23.tar.gz /home/data/vip25/software/gistic2.0`
 I run the code, and it gave the error:
`The install directory exists, exiting...`

**Comment by ShixiangWang** [comment]
The `/home/data/vip25/software/gistic2.0` exists, you should remove it firstly.

**Comment by ayue2019** [comment]
Thank you. I just installed it according to your Chinese instructions...

**Comment by ShixiangWang** [comment]
okay
