### ISSUE TITLE
no root authority 

### ISSUE THREAD

**Issue by dreammxy** [ShixiangWang/install_GISTIC#8]
Dear Wang
Thanks a lot for your script to install GISTIC. I run it on server and it succesfully gain the sample results. But when I run my own data, it failed. Then I remove the sample result file and tried run_sample_script again. It showed the same error below:
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
I wonder why it happened, is it because the root authority. Could you give me some suggestion? Thank you very much.
Maggie

**Comment by ShixiangWang** [comment]
I have no idea why it happens, the GISTIC is very picky and you should run it under the same directory where the `gistic2` file locate. That may explain why you can run the sample results but not yours.

If you still got the error, my suggestion is to run GISTIC from docker or use Hiplot plugin https://hiplot.com.cn/advance/gistic2 (which uses gistic2 docker behind).

**Comment by ShixiangWang** [comment]
I am closing this issue now because no further feedback. Please reopen it if you still need some help for this topic.
