### ISSUE TITLE
Error: Cannot locate Java Runtime Environment (JRE).

### ISSUE THREAD

**Issue by ya73** [ShixiangWang/install_GISTIC#9]
Dear Shixiang

I followed the instructions but had this error:

```
Error: Cannot locate Java Runtime Environment (JRE).
The directory /new_gistic/MCR_Installer/sys/java/jre/maci64/jre does not exist.

==================================
Seting environmanet variables..
==================================
==================
    Testing...  
Please be patient
==================
--- creating output directory ---
--- running GISTIC ---
Setting Matlab MCR root to /Users/usef/Desktop/new_gistic/MATLAB_Compiler_Runtime
./gistic2: line 19: ./gp_gistic2_from_seg: cannot execute binary file
Test failed, please check the errors above.
Typically, the errors are due to lack of some system dependencies.
    Please search the QA on internet or file to https://github.com/ShixiangWang/install_GISTIC/issues






=======
```

I found that MCR_Installer/sys/java/jre/maci64/jre does not exists, instead MCR_Installer/sys/java/jre/glnxa64/jre is there!!

How can I get gistic installed?

Thanks for the help..

**Comment by ShixiangWang** [comment]
@ya73 Hi, based on my previous experience, the GISTIC2 can only run on Linux OS. It seems that you are using MacOS.

So my suggestion is either using docker to install GISTIC2 as [README](https://github.com/ShixiangWang/install_GISTIC/blob/master/README.md) described or directly using the GISTIC plugin on the hiplot platform https://hiplot.com.cn/advance/gistic2

Hope it helps.

**Comment by ya73** [comment]
Thank you for your quick response.

Yes, I use my Mac.

So will it be an ideal solution to use on a cluster?

Thanks

**Comment by ShixiangWang** [comment]
Yeah.

**Comment by ya73** [comment]
I got this error when I made the attempt on the hpc cluster..

./gp_gistic2_from_seg: error while loading shared libraries: libmwlaunchermain.so: cannot open shared object file: No such file or directory

**Comment by ShixiangWang** [comment]
@ya73 Sorry, I missed this message. Thanks for your feedback. The guide should work as I tested it on Linux and deploy a docker image https://github.com/ShixiangWang/install_GISTIC/blob/master/Dockerfile. I think after you installed this tool, you should only run the tool from the GISTIC directory.
